'use client';

import { AnimatePresence } from 'motion/react';
import * as m from 'motion/react-m';
import { useCallback, useSyncExternalStore } from 'react';
import { DemoBadge } from '@/components/ui/demo-badge';
import { memorySink } from '@/lib/analytics';
import { useLocale } from '@/lib/i18n/locale-provider';
import type { TrackedEvent } from '@/types/analytics';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * LIVE EVENT STREAM.
 *
 * This reads the in-memory analytics ring buffer, so it shows the events THIS
 * VISITOR just generated by browsing the store.
 *
 * It is the single most persuasive thing on the dashboard, and it costs
 * essentially nothing: a business owner clicks through a few products, adds
 * something to the bag, opens this page, and watches their own session appear.
 * A static screenshot of "analytics" proves nothing; this proves the event
 * layer is real even though the figures above it are not.
 *
 * Session-only. Held in memory, never persisted, never transmitted.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const EVENT_TONE: Record<string, string> = {
  add_to_cart: 'text-positive',
  checkout_completed: 'text-positive',
  remove_from_cart: 'text-negative',
  checkout_started: 'text-ember',
  ai_assistant_opened: 'text-ember',
  ai_assistant_query: 'text-ember',
};

/** Stable empty reference: a fresh [] each call would loop useSyncExternalStore. */
const NO_EVENTS: TrackedEvent[] = [];

export function EventFeed({
  copy,
}: {
  copy: { title: string; subtitle: string; empty: string; note: string };
}) {
  const { locale } = useLocale();

  // The ring buffer IS an external store, so this is the primitive built for
  // it: no seeding effect, no setState cascade, and a correct server snapshot
  // (empty) so the prerendered HTML matches the first client render.
  const subscribe = useCallback(
    (onChange: () => void) => memorySink.subscribe(onChange),
    [],
  );
  const events = useSyncExternalStore(
    subscribe,
    () => memorySink.snapshot(),
    () => NO_EVENTS,
  );

  const time = (ts: number) =>
    new Intl.DateTimeFormat(locale === 'es' ? 'es-ES' : 'en-GB', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    }).format(new Date(ts));

  return (
    <section aria-labelledby="event-feed-heading" className="flex h-full flex-col">
      <header className="mb-6 flex items-start justify-between gap-4">
        <div>
          <h2 id="event-feed-heading" className="label text-ink">
            {copy.title}
          </h2>
          <p className="micro-label mt-2 flex items-center gap-2 text-ember">
            <span className="size-1.5 animate-[atl-pulse-soft_1.8s_ease-in-out_infinite] rounded-pill bg-ember" />
            {copy.subtitle}
          </p>
        </div>
        <DemoBadge />
      </header>

      {events.length === 0 ? (
        <p className="reading text-small text-ink-muted">{copy.empty}</p>
      ) : (
        <ul className="flex max-h-96 flex-col overflow-y-auto overscroll-contain">
          <AnimatePresence initial={false}>
            {events.slice(0, 30).map((event) => (
              <m.li
                key={event.id}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.22, ease: [0.16, 1, 0.3, 1] }}
                className="flex items-baseline gap-3 border-b border-hairline py-2.5"
              >
                <span className="micro-label shrink-0 text-ink-subtle" data-numeric>
                  {time(event.ts)}
                </span>
                <span
                  className={`micro-label shrink-0 ${EVENT_TONE[event.event.name] ?? 'text-ink'}`}
                >
                  {event.event.name}
                </span>
                <span className="micro-label truncate text-ink-subtle">{event.path}</span>
              </m.li>
            ))}
          </AnimatePresence>
        </ul>
      )}

      <p className="micro-label mt-5 text-ink-subtle">{copy.note}</p>
    </section>
  );
}
